
services:
  joonik_front:
    image: node:18
    container_name: joonik_front
    working_dir: /app
    entrypoint: /bin/bash
    restart: always
    volumes:
      - .:/app
    ports:
      - '8402:8080'
    tty: true
    #command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true

  joonik_front_prod:
    image: nginx:stable-alpine
    container_name: joonik_front_prod
    volumes:
      - ./dist:/usr/share/nginx/html # Sirve los archivos generados por el build
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8403:80'
    networks:
      - joonik_front_red
      
networks:
  joonik_front_red:
    driver: bridge
